# Generated by Django 2.2.7 on 2019-12-05 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='Hash',
            field=models.CharField(default='afded935553c74e41b12fff1cc1bbabdfd9c4fa5b638ca8d75a32dab492a3f88', max_length=256),
        ),
        migrations.AddField(
            model_name='block',
            name='delta',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='block',
            name='isMined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='nonce',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='block',
            name='prevHash',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 18, 35, 38, 691550), verbose_name='creation date'),
        ),
    ]
