# Generated by Django 2.2.7 on 2019-12-05 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_auto_20191205_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='Hash',
            field=models.CharField(default='e6167511434d5a00703adaf7cf04ad1d6e5372e52aca114b6cb73770f9aa2286', max_length=256),
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 18, 39, 7, 896545), verbose_name='creation date'),
        ),
    ]
