# Generated by Django 2.2.7 on 2019-12-05 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_auto_20191205_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='Hash',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='block',
            name='delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='block',
            name='isMined',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 21, 52, 4, 871986), verbose_name='creation date'),
        ),
    ]
