# Generated by Django 2.2.7 on 2019-12-05 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_auto_20191205_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='isMined',
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 21, 56, 46, 767740), verbose_name='creation date'),
        ),
    ]
