# Generated by Django 2.2.7 on 2019-12-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0006_auto_20191205_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='creation date'),
        ),
    ]
