# Generated by Django 2.2.7 on 2019-12-06 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0007_auto_20191205_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='solTime',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 13, 4, 46, 27616), verbose_name='creation date'),
        ),
    ]
