# Generated by Django 2.2.7 on 2019-12-06 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0009_auto_20191206_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='Hash',
        ),
        migrations.AddField(
            model_name='block',
            name='prevHashMatches',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 15, 5, 54, 688846), verbose_name='creation date'),
        ),
    ]
