# Generated by Django 2.2.7 on 2019-12-06 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0011_auto_20191206_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 23, 32, 37, 376455), verbose_name='creation date'),
        ),
    ]
