# Generated by Django 2.2.7 on 2019-12-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0012_auto_20191206_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(verbose_name='creation date'),
        ),
    ]
