# Generated by Django 2.2.7 on 2019-12-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0013_auto_20191207_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='prevHash',
            field=models.CharField(default='00000', max_length=200),
        ),
    ]
